config/routes.rb
LGBTHomelessness::Application.routes.draw do

  root 'home#index'
  get 'about' => "home#about"
  get 'who_are_you' => "home#who"
  get 'volunteer' => "home#volunteer"
  get 'contact' => "home#contact"
  get 'calendar' => "home#calendar"
  get 'results' => "home#result"
  post 'contact' => "contact#create"
  post 'volunteer' => 'volunteer#create'
  get 'volunteers' => "volunteer#index"
  get 'org_list' => "home#org_list"
  get 'wish_lists' => "home#wish_lists"
  get 'donate_money' => "home#donate_money"
  get 'give_help' => "home#give_help"

  post 'sms_request' => "sms#received"
  get  'sms_test'    => "sms#test"

  resources :organizations do
      resources :programs
  end

  resources :programs

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :programs

  def friendliness_ratings
    programs.collect{|p| p.friendliness_rating}.uniq
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ActionController::Base
  respond_to :json, :html
  layout "application"


  def index
    query = Program
    if(params[:age])
      query = query.age_range(params[:age])
    end

    if(params[:sex])
      query = query.gender_required(params[:sex])
    end

    if(params[:orientation])
      query = query.sexual_orientation_required(params[:orientation])
    end

    if(params[:spanish])
      query = query.language_needed(params[:spanish])
    end

    if(params[:services_group])
      #query = Program.service_query(query, params[:services_group].join(",").split(","))
      query = query.services_offered(params[:services_group].join(",").split(","))
    end

    @organizations = query.collect{|p| p.organization}.uniq
    respond_with @organizations
  end

  def edit
    @organization= Organization.find(params[:id])
  end

  def update
    binding.pry
    o = Organization.update(params[:id], organization_params)
    redirect_to o
  end

  def create
    @organization = Organization.create(organization_params)
    redirect_to @organization
  end

  def organization_params
    params[:organization].permit([:name, :description, :address, :address2, :city, :state, :zip, :phone_no, :website, :email, :latitude, :longitude])
  end

  def new
    @organization = Organization.new
    @organizations = query.collect{|p| p.organization}.uniq
    
    respond_with @organizations
  end

  def show
    @organization = Organization.find(params[:id])
    respond_with @organization
  end
end

app/views/organizations/edit.html.erb
<%= bootstrap_form_for(@organization, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>
  <%= f.text_field :name %>
  <%= f.text_area :description %>
  <%= f.text_field :address %>
  <%= f.text_field :address2 %>
  <%= f.text_field :city %>
  <%= f.text_field :state %>
  <%= f.text_field :zip %>
  <%= f.telephone_field :phone_no %>
  <%= f.url_field :website %>
  <%= f.email_field :email %>
  <%= f.text_field :latitude %>
  <%= f.text_field :longitude %>
  <%= f.submit %>
<% end %>

app/views/organizations/index.html.erb
<div class="main col-lg-1">
  &nbsp;
</div>
  <div class="main col-lg-10">

  <% unless @organizations.empty? %>
      <%=
         first_valid  = @organizations.select{|o| o.latitude}.first
         if first_valid
           map(:center => {
             :latlng => [first_valid.latitude, first_valid.longitude],
             :zoom => 10,
           },
           :tile_layer => "http://openmapsurfer.uni-hd.de/tiles/roads/x={x}&y={y}&z={z}",
           :markers => @organizations.select{|o| o.latitude and o.longitude }.collect{|o| {:latlng => [o.latitude, o.longitude]}},
           :max_zoom => 15
           )
        end

       %>

      <ul class='list-group results'>
        <% @organizations.each do |organization| %>

          <li class='list-group-item place sortable' data-lat='<%= organization.latitude || "" %>' data-lng= '<%= organization.longitude || "" %>' >
            <%= link_to organization.name, organization %>

            <span class="friendliness">
                <% organization.friendliness_ratings.each do |rating|%>
                  <% if rating == "LGBT Focused" %>
                    <%= image_tag("lgbt_focused.png", :alt => "LGBT Focused", :title => "LGBT Focused") %>
                  <%end%>
                  <% if rating == "LGBT Friendly" %>
                    <%= image_tag("lgbt_friendly.png", :alt => "LGBT Friendly", :title => "LGBT Friendly") %>
                  <%end%>
                <%end%>

            </span>

            <span class="badge"><%=organization.programs.count%></span>

          </li>
        <%end%>
      </ul>
  <%else%>
    <h2>No results found</h2>
  <%end%>
</div>
<div class="main col-lg-1">
  &nbsp;
</div>

app/views/organizations/new.html.erb
<%= bootstrap_form_for(@organization, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>
  <%= f.text_field :name %>
  <%= f.text_area :description %>
  <%= f.text_field :address %>
  <%= f.text_field :address2 %>
  <%= f.text_field :city %>
  <%= f.text_field :state %>
  <%= f.text_field :zip %>
  <%= f.telephone_field :phone_no %>
  <%= f.url_field :website %>
  <%= f.email_field :email %>
  <%= f.text_field :latitude %>
  <%= f.text_field :longitude %>
  <%= f.submit %>
<% end %>

app/views/organizations/show.html.erb
<div class="main col-lg-5">
    <h1><%=@organization.name%></h1>

  <% if @organization.latitude and @organization.longitude %>
      <%= map(:center => {
            :latlng => [@organization.latitude, @organization.longitude],
            :zoom => 12,
          },
          :tile_layer => "http://openmapsurfer.uni-hd.de/tiles/roads/x={x}&y={y}&z={z}",
          :markers => [{
              :latlng => [@organization.latitude, @organization.longitude]
          }],
          :max_zoom => 16
      ) %>
      <a class='directions' href="http://maps.apple.com/?ll=<%=@organization.latitude%>,<%=@organization.longitude%>">Directions</a>
  <%end%>

</div>

<div class="main col-lg-5">

  <h2>Programs</h2>
  <%@organization.programs.each do |program| %>
    <% if program.name == "" %>
      <li><%=link_to @organization.name, program_path(program.id) %> </li>
    <%else%>
      <li><%=link_to program.name, program_path(program.id)%> </li>
    <%end%>
  <%end%>

  <%if @organization.description %>
      <h2>Description</h2>
      <P><%= @organization.description %></p>
  <%end%>

  <%=render partial: 'shared/org_contact_info', locals: {organization: @organization}%>

  <% if @organization.latitude and @organization.longitude %>
    <p class='place' data-lat='<%= @organization.latitude || "" %>' data-lng= '<%= @organization.longitude || "" %>' >You are currently  </p>
  <%end%>

</div>
<div class="main col-lg-2">
    <A HREF="/contact?flag_inaccurate_org=<%= @organization.id %>"><%= image_tag("flag_red.png", :alt => "Flag as Inaccurate", :title => "Flag as inaccurate") %> Flag as Inaccurate</a>
</div>